import { createElement } from '@lwc/engine-dom';
import BankAccountComponentV2 from 'c/bankAccountComponentV2';

describe('c-bank-account-component-v-2', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-bank-account-component-v-2', {
            is: BankAccountComponentV2
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});